name: Visual Regression
on: [push, pull_request]

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - run: yarn install
      - run: yarn build-prod
      - run: yarn bundle-size
      - run: yarn eyes-storybook
